### ISSUE TITLE
Add option to only mark "whole words"

### ISSUE THREAD

**Issue by vmalloc** [magnars/mark-multiple.el#12]
Currently mark-multiple selects parts of words, which in many cases is not very useful (e.g. programming).

**Comment by magnars** [comment]
That's a good idea. Now mark-multiple is deprecated, but it might be a nice expansion for multiple-cursors.

**Comment by vmalloc** [comment]
Should I open another issue for multiple-cursors?

**Comment by magnars** [comment]
Ah, yes, that would be great. Thanks. I'll close this then.
