### ISSUE TITLE
Mark multiple and auto-complete do not mingle well in ESS's R-mode

### ISSUE THREAD

**Issue by mattfidler** [magnars/mark-multiple.el#13]
mark-multiple mc/mark-next-like-this does not mark the next occurrence correctly.

In a R-mode buffer, if I have

```
## TH 1
abcd
## TH 2
efg
## TH 3
```

I select the first TH and then mark-next-like-this to select the second TH.  After that I repeat the command and it selects the abcd line.

I have auto-complete enabled for R.  When I disable auto-comlpete-mode, it works correctly.  A work-around would be to disable auto-complete-mode before running mc/mark-next-like-this for example:

```
(defadvice mc/mark-next-like-this (around fix-issue)
  (let ((ac-on (and (boundp 'auto-complete-mode) auto-complete-mode)))
    (when ac-on
      (auto-complete-mode -1))
    ad-do-it
    (when ac-on
      (auto-complete-mode 1))))
```

However this still doesn't work for me.

**Comment by magnars** [comment]
Looks like you're using multiple-cursors, which is good since mark-multiple is discontinued. Would you mind opening the issue there? Thanks :-)
