### ISSUE TITLE
js2-rename-vars is missing

### ISSUE THREAD

**Issue by aL3xa** [magnars/mark-multiple.el#2]
Hi @magnars ! First of all, thanks for utterly useful emacs mode and great videos on Emacs Rocks!

Now, I know that I may just talk rubbish, but I can't find `js2-rename-var` in `mark-multiple`. What's the catch?

**Comment by magnars** [comment]
Hi Aleksandar! I'm glad you like it. :-)

I should have made it more clear, but `js2-rename-var` has been moved to `js2-refactor.el` at https://github.com/magnars/js2-refactor.el

Sorry about the confusion - I'll update the readme.

**Comment by aL3xa** [comment]
Okay, thnx! And I'll give `js2-refactor` a try, since it sounds very tempting! =)
