### ISSUE TITLE
packaging?

### ISSUE THREAD

**Issue by zenspider** [magnars/mark-multiple.el#3]
Is it possible (and practical) to make this an installable package?

**Comment by magnars** [comment]
The original intent was for this to be a library for developers of emacs extensions, but I'm finding that the built in examples are very useful like they stand.

I'm not personally using package.el, but I figure as long as you're setting up your own keybindings, it's no big deal to just require all of the extensions.

What are your thoughts on the matter?

**Comment by zenspider** [comment]
On Feb 26, 2012, at 04:07 , Magnar Sveen wrote:

> The original intent was for this to be a library for developers of emacs extensions, but I'm finding that the built in examples are very useful like they stand.
> 
> I'm not personally using package.el, but I figure as long as you're setting up your own keybindings, it's no big deal to just require all of the extensions.
> 
> What are your thoughts on the matter?

I watched your video on expand-region and was able to pop this into my emacs setup and just go with it:

``` elisp
(and (rwd-install-package 'expand-region)
     (global-set-key (kbd "M-SPC")   'er/expand-region))
```

It was fantastic that I could just do that and run with it. After watching your latest vid on mark-multiple I'd have to say that this feature stands on its own two feet and should be easily available.

**Comment by magnars** [comment]
Sounds good. I've added this to my todo-list. Since I'm in the process of selling my house, which is draining all my spare time, I can't give a decent timeframe unfortunately.

**Comment by bodil** [comment]
Consider submitting it to https://github.com/milkypostman/melpa at least - MELPA can build from git repos, so there's no release process hassle once it's in.

**Comment by Gozala** [comment]
I also would really love to have this installable.

**Comment by magnars** [comment]
I am working on deprecating mark-multiple and replacing it with multiple-cursors, which has a much saner implementation of this functionality. That will definitely be available in the various installable forms.
