### ISSUE TITLE
 Invalid read syntax: "?"

### ISSUE THREAD

**Issue by mbuczko** [magnars/mark-multiple.el#5]
emacs 24 (on windows 7) complains about these 2 lines:

```
((or (eq base 'up) (eq base ?ĂĽ))
```

and

```
((or (eq base 'down) (eq base ?ĂŚ))
```

in mark-more-like-this.el throwing a message: `Invalid read syntax: "?"`

**Comment by magnars** [comment]
Seems like it my norwegian characters have been mutilated somewhere along the line. This is what it looks like here:

```
((or (eq base 'down) (eq base ?æ))
```

However, my peculiar norwegian keyboard should definitely not be making its way into my public emacs packages, so I'll remove them promptly. 

Thanks for the report!
