### ISSUE TITLE
Breaks Pabbrev

### ISSUE THREAD

**Issue by prenaux** [magnars/mark-multiple.el#6]
Hi, great mode, however there's an issue when it is used with Pabbrev, pabbrev shows autocompetion candidates directly into the buffer which mess up the text when used with a multi-mark (tried with C-x r t & C->/<).

You should be able to test pretty easily:
(require 'pabbrev)
(global-pabbrev-mode)
(setq pabbrev-idle-timer-verbose nil)

Then try to use a multi-mark command...

I think pabbrev is bundled with the Emacs 23/24 -- not sure.

A simple fix would be to toggle pabbrev on/off when entering mark mode, maybe they already are some hooks I can use for that... I would have checked/fixed myself but my elisp is "hack 'till it works" level, I'm sure you can find a cleaner solution than what I could come up with.

**Comment by magnars** [comment]
Thanks for an excellent report, this should make it easy to look into. I'll have a go at it when I get home from work.

**Comment by magnars** [comment]
I've now studied this for a bit, and I'm not seeing any elegant solution. It seems to be a matter of turning off pabbrev-mode when entering mark-multiple-mode, and then turning it back on again after. But we need to check if 1) it is installed, 2) it is on, before doing so. Which is basically the 'hack-it-till-it-works" solution.

**Comment by prenaux** [comment]
Maybe we could just have "pre/post" "go into multi-mark" mode hooks so I can put that or other things in there if I need to.

**Comment by magnars** [comment]
That would certainly make it more extensible. Good suggestion! I'll get to implementing that later tonight.

**Comment by prenaux** [comment]
Thanks, this works nicely for me.

**Comment by magnars** [comment]
Great :-)
