### ISSUE TITLE
Something about mark-multiple.el

### ISSUE THREAD

**Issue by ghost** [magnars/mark-multiple.el#7]
I am new to emacs and elisp but enjoying looking for useful emacs plugins like mark-multiple. I have some questions about mark-multiple:

1.Skip some next/previous substrings like:

```
abc
abc-config
abc
```

How can I skip the second 'abc' but mark the first and third 'abc' ?

2.Sometimes the text is to long, if marking previous/next can scroll the screen at the same time that will be awesome.

3.Sometimes I press 'C->' too fast and want to cancel marking some, how can I do that ?

I am new to elisp and confused by the document string. So I hope I can find an answer here.
If some of these are not provided in the current version I will be glad to see them in the next release. :)

**Comment by magnars** [comment]
Hello, and welcome to the wonderful world of emacs :-)
1. You can skip the latest mark by giving mark-next-like-this a prefix-command of 0. `C-0 C->`
2. You can scroll a little bit by pressing `C-l` (that's a lowercase L) a couple times, but scrolling far is difficult with the way mark-multiple is implemented now. I am working on a replacement (multiple-cursors) that can do this pretty easily.
3. You can cancel the latest mark by giving mark-next-like-this a prefix-command of -1. `C-- C->`

There is also (mark-more-like-this-extended) that you can bind to some key, and it will allow you to quickly mark/skip/delete by using the arrow keys. It's a bit wonky at first, but works very well.

**Comment by ghost** [comment]
Really thanks for your answer ! And I am going to have a look at multiple-cursors ! :)
