### ISSUE TITLE
`inline-string-rectangle' does not replace the content of the rectangle as `string-rectangle' does

### ISSUE THREAD

**Issue by jlf** [magnars/mark-multiple.el#8]
Per our discussion on IRC, inline-string-rectangle requires use of delete-selection-mode to replace the existing contents of a rectangle.  When delete-selection-mode is not in effect the new rectangle content is appended to the original content.

**Comment by magnars** [comment]
Please try now. :-) I skipped the more feature-rich `C-g` integration you mentioned, since multiple-cursors is replacing this library. The new-and-improved way of getting this functionality is with rectangular-region-mode from multiple-cursors.

**Comment by jlf** [comment]
Perfect, thanks!
